### ISSUE TITLE
Please use POST method :)

### ISSUE THREAD

**Issue by daerbiubiu** [ifyour/deeplx-for-cloudflare#1]
按照read.md通过worker部署后打开网页提示，求解是哪里出问题了吗

**Comment by ZongyaoRen** [comment]
加1

**Comment by ZEERDEER** [comment]
我也是这样

**Comment by ZongyaoRen** [comment]
> 我也是这样

我找到了原因，出现“Please use POST method :)”是代码work的表现，在翻译软件（如沉浸式翻译）中API URL输入：https://xxxx.xxxx.workers.dev/translate 即可。注意不要直接复制worker pagers的地址

**Comment by ifyour** [comment]
是的，当你看到这个提示的时候是 GET 请求，放入使用到该 API 的应用中即可（POST 请求）。
