### ISSUE TITLE
服务返回错误：403， 说明暂时没有权限访问该服务。

### ISSUE THREAD

**Issue by duron9000** [ifyour/deeplx-for-cloudflare#2]
部署后，使用chrome插件 {沉浸式翻译}, 测试API 提示出错，是哪里有问题？

服务返回错误：429，说明请求过于频繁或超出额度限制，请稍后再试。 {"code":429,"data":null,"message":"Too many requests, please try again later."}

几个小时后，自动OK了。

**Comment by smark-d** [comment]
应该是CF IP切换的问题

**Comment by ifyour** [comment]
多尝试几次，429（请求频繁） 的话暂时没有好的解决方案，有进展了我会通知大家的。
