### ISSUE TITLE
方案可能存在缺陷，不是真的用 Worker 去请求 deepl 的

### ISSUE THREAD

**Issue by miantiao-me** [ifyour/deeplx-for-cloudflare#3]
我看了下方案，实质上是用 Worker 做 CDN 然后回源 Vercel, 用 Vercel 去请求 deepl 。

这样如果 Vercel 出口 IP 不够多，就会被 deepl 拦截，产生 429 错误， 看到 Twitter 上也有讨论了。

套一层 CF 没必要，直接部署在 Vercel Runtime 也可以运行的，刚刚部署了一份，已经跑起来了，感谢贡献 deeplx 包。

目前存在的问题是 Vercel Runtime 的出口 IP 是否够多，暂时没遇到 429, 等遇到了再来反馈。

**Comment by ifyour** [comment]
你说的没错，因为不能直接在 CF 请求 DeepL 服务，存在一个[握手失败](https://github.com/cloudflare/workerd/issues/776)的问题（525错误），所以我加了一层代理。

> 直接部署在 Vercel Runtime 也可以运行的

这个能否详细做下测试，试试用该 API 翻译一本书看看，我最初的想法也是想利用 CF 的出口 IP 非常多的优势，避免 429 的问题，套了一层代理后，全部走代理了，CF 只做了 CDN 加速的功能。😂

**Comment by ifyour** [comment]
CF 官方如果解决了这个 bug，那直接部署 DeepLX 应该就能生效了，不需要走 Vercel 代理。

**Comment by miantiao-me** [comment]
> 你说的没错，因为不能直接在 CF 请求 DeepL 服务，存在一个[握手失败](https://github.com/cloudflare/workerd/issues/776)的问题（525错误），所以我加了一层代理。
> 
> > 直接部署在 Vercel Runtime 也可以运行的
> 
> 这个能否详细做下测试，试试用该 API 翻译一本书看看，我最初的想法也是想利用 CF 的出口 IP 非常多的优势，避免 429 的问题，套了一层代理后，全部走代理了，CF 只做了 CDN 加速的功能。😂

是的。我也在 Worker 部署了。同样遇到了 525  的问题，看着是 SSL 签名相关的错误，靠 JS 层面应该是解决不了了。等 CF 修复吧

**Comment by ifyour** [comment]
另外可以试试 zu1k 大佬的 [IPV6 代理池](https://zu1k.com/posts/tutorials/http-proxy-ipv6-pool/)方案，后面我研究下看看怎么利用，手里刚好有个 VPS 有 IPV6 😎

**Comment by miantiao-me** [comment]
> 另外可以试试 zu1k 大佬的 [IPV6 代理池](https://zu1k.com/posts/tutorials/http-proxy-ipv6-pool/)方案，后面我研究下看看怎么利用，手里刚好有个 VPS 有 IPV6 😎

尝试翻译了一下 https://www.rfc-editor.org/rfc/rfc9113.html , 就出现了 429 ，但是过一会恢复了， 应该是单个出口 IP 被封禁了

```
{"code":429,"data":null,"message":"Too many requests, please try again later."}
```

**Comment by ifyour** [comment]
> https://api.deeplx.org/translate

我看到有个大佬突破了这个 429 的限制，但是是闭源的，不知道是怎么绕过的。😂

**Comment by miantiao-me** [comment]
> > https://api.deeplx.org/translate
> 
> 我看到有个大佬突破了这个 429 的限制，但是是闭源的，不知道是怎么绕过的。😂

公开后，可能会被官方封。

**Comment by lol2025** [comment]
> > https://api.deeplx.org/translate
> 
> 我看到有个大佬突破了这个 429 的限制，但是是闭源的，不知道是怎么绕过的。😂

这个我知道，超级简单，很早之前deepl有机制封杀，去年开始deepl就不怎么管了，就是让你搞的。估计是等用得人多了，再杀熟，然后让你们付费。
