### ISSUE TITLE
出现401

### ISSUE THREAD

**Issue by towelong** [ifyour/deeplx-for-cloudflare#6]
<img width="1176" alt="image" src="https://github.com/ifyour/deeplx-for-cloudflare/assets/41502558/b4f65698-d86c-428d-aef1-609329171552">

**Comment by ifyour** [comment]
重新部署试试，我刚测试没问题。

<img src="https://images.mingming.dev/file/a6d86773fba350eecb78d.png" width=600 />

**Comment by towelong** [comment]
> 重写部署试试，我刚测试没问题。
> 
> <img alt="" width="600" src="https://camo.githubusercontent.com/bf109e48c7ce238c33e68bb553c4e87eb54f9d567b96be1fb6aec0c84e6c0262/68747470733a2f2f696d616765732e6d696e676d696e672e6465762f66696c652f6136643836373733666261333530656563623738642e706e67">

我之前用的老的worker的方式，代码是打包混淆之后的

**Comment by ifyour** [comment]
我知道了，估计是那个忘记更新了，建议用 `npm run deploy` 重新部署。

**Comment by towelong** [comment]
> 我知道了，估计是那个忘记更新了，建议用 `npm run deploy` 重新部署。

能打包一份出来吗？ 那种方便一点

**Comment by ifyour** [comment]
[5268e2d](https://github.com/ifyour/deeplx-for-cloudflare/commit/5268e2d5ff12766a1468d987e1b96bc40cc2b1b5) 已支持，打包后的代码参考 dist/index.js。
